### ISSUE TITLE
Does not compile in CLJS

### ISSUE THREAD

**Issue by den1k** [thi-ng/geom#25]
geom/color/math, none compiles from a .cljs file

lein deps:
```
                 [org.clojure/clojure "1.7.0"]
                 [org.clojure/clojurescript "1.7.122"]
                 [figwheel-sidecar "0.4.0"]
                 [thi.ng/color "1.0.0"]
```

Filename: `core.cljs`

Content:
```
(ns geom-test.core
  (:require [thi.ng.color.core :as col]))
```

Exception:
```
Exception in thread "main" clojure.lang.ExceptionInfo: No such namespace: thi.ng.color.core, could not locate thi/ng/color/core.cljs, thi/ng/color/core.cljc, or Closure namespace "thi.ng.color.core" {:tag :cljs/analysis-error}, compiling:(/Users/den/Dropbox/dev/code/vimsical/geom-test/script/repl.clj:3:1)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$script_opt.invoke(main.clj:337)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: clojure.lang.ExceptionInfo: No such namespace: thi.ng.color.core, could not locate thi/ng/color/core.cljs, thi/ng/color/core.cljc, or Closure namespace "thi.ng.color.core" {:tag :cljs/analysis-error}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at cljs.analyzer$error.invoke(analyzer.cljc:543)
	at cljs.analyzer$error.invoke(analyzer.cljc:541)
	at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:1649)
	at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:2485)
	at cljs.analyzer$analyze_STAR_$fn__2091.invoke(analyzer.cljc:2566)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:333)
	at clojure.core$reduce.invoke(core.clj:6518)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2566)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2581)
	at cljs.analyzer$analyze_file$fn__2142.invoke(analyzer.cljc:2825)
	at cljs.analyzer$analyze_file.invoke(analyzer.cljc:2820)
	at figwheel_sidecar.repl$analyze_build.invoke(repl.clj:242)
	at figwheel_sidecar.repl$analyze_builds.invoke(repl.clj:247)
	at figwheel_sidecar.repl$run_autobuilder_helper.invoke(repl.clj:295)
	at figwheel_sidecar.repl$start_autobuild.invoke(repl.clj:366)
	at figwheel_sidecar.repl$start_repl.invoke(repl.clj:466)
	at figwheel_sidecar.repl$cljs_repl.invoke(repl.clj:488)
	at figwheel_sidecar.repl$cljs_repl.invoke(repl.clj:475)
	at figwheel_sidecar.repl_api$cljs_repl.invoke(repl_api.clj:77)
	at user$eval16094.invoke(repl.clj:3)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	... 14 more```

**Comment by den1k** [comment]
Works after local install of `[thi.ng/geom "0.0.882"]`

```
git clone git@github.com:thi-ng/geom.git
cd geom
./tangle-all.sh
./install-all.sh
```

**Comment by postspectacular** [comment]
Hiya, am confused - can you please point me to your project and I will investigate. Right now I can't tell you what's going on... thanks!

**Comment by den1k** [comment]
@postspectacular 

https://github.com/den1k/geom-example

```
➜  geom-example git:(master) ✗ lein figwheel
Figwheel: Starting server at http://localhost:3449
Focusing on build ids: dev
Compiling "resources/public/js/compiled/geom_example.js" from ["src"]...
Compiling "resources/public/js/compiled/geom_example.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:target/figwheel_temp/dev/figwheel/connect.cljs
 at clojure.core$ex_info.invoke (core.clj:4593)
Caused by: clojure.lang.ExceptionInfo: No such namespace: thi.ng.geom.viz.core, could not locate thi/ng/geom/viz/core.cljs, thi/ng/geom/viz/core.cljc, or Closure namespace "thi.ng.geom.viz.core"
 at clojure.core$ex_info.invoke (core.clj:4593)

clojure.lang.ExceptionInfo: No such namespace: thi.ng.geom.viz.core, could not locate thi/ng/geom/viz/core.cljs, thi/ng/geom/viz/core.cljc, or Closure namespace "thi.ng.geom.viz.core" {:tag :cljs/analysis-error}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at cljs.analyzer$error.invoke(analyzer.cljc:543)
	at cljs.analyzer$error.invoke(analyzer.cljc:541)
	at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:1649)
	at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:2485)
	at cljs.analyzer$analyze_STAR_$fn__2089.invoke(analyzer.cljc:2566)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:333)
	at clojure.core$reduce.invoke(core.clj:6518)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2566)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2581)
	at cljs.analyzer$analyze_file$fn__2140.invoke(analyzer.cljc:2825)
	at cljs.analyzer$analyze_file.invoke(analyzer.cljc:2820)
	at figwheel_sidecar.repl$analyze_build.invoke(repl.clj:242)
	at figwheel_sidecar.repl$analyze_builds.invoke(repl.clj:247)
	at figwheel_sidecar.repl$run_autobuilder_helper.invoke(repl.clj:295)
	at figwheel_sidecar.repl$start_autobuild.invoke(repl.clj:366)
	at figwheel_sidecar.repl$run_autobuilder.invoke(repl.clj:576)
	at user$eval16119.invoke(form-init5114583419288522768.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Subprocess failed
```

**Comment by postspectacular** [comment]
Erm... your `project.clj` doesn't list geom as a dependency, so of course the namespace can't be found. If I add `[thi.ng/geom "0.0.881"]` to the `:dependencies` it compiles fine...

Also, note - this 0.0.881 version is the latest release and still uses an older version of the thi.ng/color lib (v1.0.0 of the color lib has only been released last week and has a completely different API than the previous 0.2.1 release). The dev branch of this repo (geom) has already been updated to use the new color API, but I will do some more refactoring before cutting a new release...

**Comment by den1k** [comment]
oh, apologies. I figure the issue I had before was part of intellij not indexing the new project file...
Thanks!
