### ISSUE TITLE
JOGL examples not working

### ISSUE THREAD

**Issue by mourginakis** [thi-ng/geom#94]
Trying to run any of the JOGL examples results in an error, it seems that jogamp for whatever reason cannot be loaded into the namespace

#### stack trace upon trying to load examples/jogl/stl_mesh.clj

```
CompilerException java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/b7/8gchdr29163fj3sl6cjqn0_m0000gn/T/jogamp_0000/file_cache/jln13507248069143319711/jln4324653017614860419/natives/macosx-universal/libgluegen-rt.jnilib, compiling:(core.clj:81:1) 
ERROR: Unhandled REPL handler exception processing message {:nrepl.middleware.print/stream? 1, :nrepl.middleware.print/print cider.nrepl.pprint/pprint, :nrepl.middleware.print/quota 1048576, :nrepl.middleware.print/buffer-size 4096, :nrepl.middleware.print/options {:right-margin 70}, :op stacktrace, :session 223e9410-21f4-4482-8d59-a107ef924db1, :id 8}
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.common.os.Platform
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at clojure.core$deref_future.invokeStatic(core.clj:2292)
	at clojure.core$future_call$reify__8097.deref(core.clj:6894)
	at clojure.core$deref.invokeStatic(core.clj:2312)
	at clojure.core$pmap$step__8110$fn__8114.invoke(core.clj:6945)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$map$fn__5591.invoke(core.clj:2749)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:706)
	at clojure.core$next__5108.invokeStatic(core.clj:64)
	at clojure.core.protocols$fn__7852.invokeStatic(protocols.clj:169)
	at clojure.core.protocols$fn__7852.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__7807$G__7802__7816.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__7835.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6748)
	at clojure.core$into.invokeStatic(core.clj:6815)
	at clojure.core$mapv.invokeStatic(core.clj:6823)
	at clojure.core$mapv.invoke(core.clj:6823)
	at cider.nrepl.middleware.stacktrace$flag_duplicates.invokeStatic(stacktrace.clj:205)
	at cider.nrepl.middleware.stacktrace$flag_duplicates.invoke(stacktrace.clj:194)
	at cider.nrepl.middleware.stacktrace$analyze_stacktrace.invokeStatic(stacktrace.clj:219)
	at cider.nrepl.middleware.stacktrace$analyze_stacktrace.invoke(stacktrace.clj:213)
	at cider.nrepl.middleware.stacktrace$analyze_cause.invokeStatic(stacktrace.clj:323)
	at cider.nrepl.middleware.stacktrace$analyze_cause.invoke(stacktrace.clj:314)
	at cider.nrepl.middleware.stacktrace$analyze_causes$fn__4401.invoke(stacktrace.clj:348)
	at clojure.core$map$fn__5583$fn__5584.invoke(core.clj:2734)
	at clojure.core$take_while$fn__5634$fn__5635.invoke(core.clj:2893)
	at clojure.lang.Iterate.reduce(Iterate.java:79)
	at clojure.core$transduce.invokeStatic(core.clj:6803)
	at clojure.core$into.invokeStatic(core.clj:6819)
	at clojure.core$into.invoke(core.clj:6807)
	at cider.nrepl.middleware.stacktrace$analyze_causes.invokeStatic(stacktrace.clj:347)
	at cider.nrepl.middleware.stacktrace$analyze_causes.invoke(stacktrace.clj:339)
	at cider.nrepl.middleware.stacktrace$handle_stacktrace.invokeStatic(stacktrace.clj:356)
	at cider.nrepl.middleware.stacktrace$handle_stacktrace.invoke(stacktrace.clj:353)
	at clojure.lang.Var.invoke(Var.java:385)
	at cider.nrepl$wrap_stacktrace$fn__2462.invoke(nrepl.clj:432)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at nrepl.middleware.interruptible_eval$interruptible_eval$fn__1284.invoke(interruptible_eval.clj:154)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at nrepl.middleware.load_file$wrap_load_file$fn__1824.invoke(load_file.clj:81)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at cider.nrepl$wrap_out$fn__2422.invoke(nrepl.clj:334)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at cider.nrepl$wrap_content_type$fn__2322.invoke(nrepl.clj:107)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at nrepl.middleware.session$add_stdin$fn__1401.invoke(session.clj:379)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at nrepl.middleware.sideloader$wrap_sideloader$fn__1905.invoke(sideloader.clj:108)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at cider.nrepl$wrap_complete$fn__2354.invoke(nrepl.clj:143)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at cider.nrepl$wrap_format$fn__2380.invoke(nrepl.clj:194)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at cider.nrepl$wrap_profile$fn__2430.invoke(nrepl.clj:343)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at cider.nrepl$wrap_apropos$fn__2338.invoke(nrepl.clj:129)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at cider.nrepl$wrap_trace$fn__2478.invoke(nrepl.clj:464)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at cider.nrepl$wrap_inspect$fn__2398.invoke(nrepl.clj:227)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at nrepl.middleware.lookup$wrap_lookup$fn__1868.invoke(lookup.clj:52)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at cider.nrepl$wrap_spec$fn__2454.invoke(nrepl.clj:416)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at cider.nrepl$wrap_macroexpand$fn__2406.invoke(nrepl.clj:287)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at cider.nrepl$wrap_version$fn__2504.invoke(nrepl.clj:504)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at cider.nrepl$wrap_debug$fn__2364.invoke(nrepl.clj:163)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at cider.nrepl$wrap_enlighten$fn__2372.invoke(nrepl.clj:190)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at nrepl.middleware.caught$wrap_caught$fn__1217.invoke(caught.clj:97)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at cider.nrepl$wrap_refresh$fn__2438.invoke(nrepl.clj:380)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at nrepl.middleware.print$wrap_print$fn__1184.invoke(print.clj:234)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at cider.nrepl$wrap_tracker$fn__2486.invoke(nrepl.clj:482)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at nrepl.middleware.session$session$fn__1386.invoke(session.clj:325)
	at nrepl.middleware$wrap_conj_descriptor$fn__949.invoke(middleware.clj:16)
	at nrepl.server$default_handler$fn__1953.invoke(server.clj:141)
	at nrepl.server$handle_STAR_.invokeStatic(server.clj:24)
	at nrepl.server$handle_STAR_.invoke(server.clj:21)
	at nrepl.server$handle$fn__1921.invoke(server.clj:41)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.common.os.Platform
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at clojure.lang.RT.classForName(RT.java:2204)
	at clojure.lang.RT.classForName(RT.java:2213)
	at clojure.lang.Compiler.maybeResolveIn(Compiler.java:7322)
	at clojure.core$ns_resolve.invokeStatic(core.clj:4336)
	at clojure.core$ns_resolve.invokeStatic(core.clj:4325)
	at clojure.core$ns_resolve.invoke(core.clj:4325)
	at cider.nrepl.inlined_deps.orchard.v0v9v1.orchard.java$resolve_class$fn__3888.invoke(java.clj:306)
	at cider.nrepl.inlined_deps.orchard.v0v9v1.orchard.java$resolve_class.invokeStatic(java.clj:306)
	at cider.nrepl.inlined_deps.orchard.v0v9v1.orchard.java$resolve_class.invoke(java.clj:300)
	at cider.nrepl.inlined_deps.orchard.v0v9v1.orchard.java$resolve_symbol.invokeStatic(java.clj:340)
	at cider.nrepl.inlined_deps.orchard.v0v9v1.orchard.java$resolve_symbol.invoke(java.clj:326)
	at cider.nrepl.middleware.stacktrace$analyze_fn.invokeStatic(stacktrace.clj:82)
	at cider.nrepl.middleware.stacktrace$analyze_fn.invoke(stacktrace.clj:61)
	at clojure.core$comp$fn__
```

Following the program's execution, it seems as if the namespace thi.ng.geom.gl.jogl.core isn't loading because it can't properly run the lines 

```
(import [com.jogamp.opengl
    GL GL2 GL3 GL4 GLProfile GLCapabilities GLAutoDrawable GLEventListener])

(def ^:private gl-profiles
  {:gl2 GLProfile/GL2
   :gl3 GLProfile/GL3
   :gl4 GLProfile/GL4})

```

I don't know enough about java or how java dependencies work to be able to further debug this issue, but I am using the latest version as I have just cloned this repo. I have run into other threads  (for java) where the same error is caused by not having JOGL on the java classpath when run. It is my understanding that lein is supposed to handle this behavior automatically.

I am also using 
```
% lein --version
Leiningen 2.9.10 on Java 17.0.2 Java HotSpot(TM) 64-Bit Server VM

% java --version
java 17.0.2 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)
```

I tried running this with different versions of java by using the :java-cmd option in project.clj, and ran into errors as well.
With java 11, I ran into the same error (if memory serves right)
With java 8, a window opened and then immediately crashed. I do not remember the error and am unable to recreate it right now.

I have run lein deps, so my dependencies are fully updated.
If I modify the project.clj file to explicitly use  
```
[org.jogamp.gluegen/gluegen-rt "2.3.2" :classifier "natives-macosx-universal"]
[org.jogamp.jogl/jogl-all "2.3.2" :classifier "natives-macosx-universal"]
```
in the dependencies, I run into a slightly more human-readable error
```
1. Caused by java.lang.ClassNotFoundException
   com.jogamp.opengl.GL3

       URLClassLoader.java:  445  java.net.URLClassLoader/findClass
   DynamicClassLoader.java:   69  clojure.lang.DynamicClassLoader/findClass
          ClassLoader.java:  587  java.lang.ClassLoader/loadClass
   DynamicClassLoader.java:   77  clojure.lang.DynamicClassLoader/loadClass
          ClassLoader.java:  520  java.lang.ClassLoader/loadClass
                Class.java:   -2  java.lang.Class/forName0
                Class.java:  467  java.lang.Class/forName
                   RT.java: 2209  clojure.lang.RT/classForName
                   RT.java: 2222  clojure.lang.RT/classForNameNonLoading
         textured_cube.clj:    1  thi.ng.geom.examples.jogl.textured-cube/eval6002/loading--auto--
         textured_cube.clj:    1  thi.ng.geom.examples.jogl.textured-cube/eval6002
         textured_cube.clj:    1  thi.ng.geom.examples.jogl.textured-cube/eval6002
             Compiler.java: 7194  clojure.lang.Compiler/eval
             Compiler.java: 7183  clojure.lang.Compiler/eval
             Compiler.java: 7653  clojure.lang.Compiler/load
                      REPL:    1  user/eval5998
                      REPL:    1  user/eval5998
             Compiler.java: 7194  clojure.lang.Compiler/eval
             Compiler.java: 7149  clojure.lang.Compiler/eval
                  core.clj: 3215  clojure.core/eval
                  core.clj: 3211  clojure.core/eval
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj: 1990  clojure.core/with-bindings*
                  core.clj: 1990  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn
                  main.clj:  437  clojure.main/repl/read-eval-print/fn
                  main.clj:  437  clojure.main/repl/read-eval-print
                  main.clj:  458  clojure.main/repl/fn
                  main.clj:  458  clojure.main/repl
                  main.clj:  368  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   84  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   56  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  152  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  218  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  217  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  833  java.lang.Thread/run
```
I am currently running on mac, but I also ran into the same problem when running on my Ubuntu machine.

**Comment by postspectacular** [comment]
Can't check this anytime soon, but think this might just be an age thing by now. I.e. these GL bindings are from 2015/16 and I know are unsupported for macos-arm64 (M1 & above). There's also not much which can be done, since the whole JOGL bindings project seems dead and this whole aspect of thi.ng/geom would need to be refactored to use LWGL or other(?) native GL wrapper libs... sorry!

**Comment by mourginakis** [comment]
Oh yeah, being on an an unsupported M1 certainly doesn't help! (didn't even think to check)
I am going to explore getting LWJGL to work with the other components of this library. This library is awesome and brilliantly fits my use case, so I really want to get 3D to work.
Thanks for the super fast response!

**Comment by postspectacular** [comment]
FWIW all the non-JOGL related parts will (should) work also in WebGL (via CLJS), e.g. see here:

https://github.com/thi-ng/geom/blob/feature/no-org/org/examples/gl/webgl.org
